title: NHBC How Tos
description: Quick Tutorials for NHBC Planning Center Users
remote_theme: just-the-docs/just-the-docs
baseurl: "/nhbc"

# Enable built-in search
search_enabled: true

# TOC settings for page-level {:toc}
toc:
  min_level: 2
  max_level: 4
