title: NHBC How Tos
description: Quick Tutorials for NHBC Planning Center Users
theme: just-the-docs

baseurl: "/nhbc"

# Enable built-in search
search_enabled: true
search:
  heading_level: 2
  previews: 3
  preview_words_before: 5
  preview_words_after: 10

# Table of contents settings
toc:
  min_level: 2
  max_level: 4
